import type { Lead } from '@/types/lead'

export const mockLeads: Lead[] = [
  {
    id: '1',
    company: 'Diamond Concrete Solutions',
    city: 'Tampa',
    state: 'FL',
    phone: '(813) 555-0123',
    email: 'info@diamondconcrete.com',
    website: 'diamondconcrete.com',
    rating: 'A+',
    opportunityScore: 95,
    assignedRep: 'Sarah Mitchell',
    status: 'qualified',
    notes: 'Large commercial contractor, actively bidding on major projects',
    createdAt: '2024-01-15T10:30:00Z',
    category: 'Concrete & Epoxy',
    address: '1234 Industrial Blvd',
    revenue: 250000,
    lat: 27.9506,
    lng: -82.4572
  },
  {
    id: '2',
    company: 'Elite Flooring Pros',
    city: 'Orlando',
    state: 'FL',
    phone: '(407) 555-0198',
    email: 'contact@eliteflooring.com',
    website: 'eliteflooring.com',
    rating: 'A+',
    opportunityScore: 92,
    assignedRep: 'Mike Chen',
    status: 'proposal',
    notes: 'Looking for epoxy solutions for warehouse projects',
    createdAt: '2024-01-14T14:20:00Z',
    category: 'Flooring',
    address: '5678 Commerce Way',
    revenue: 180000,
    lat: 28.5383,
    lng: -81.3792
  },
  {
    id: '3',
    company: 'Precision Epoxy Coatings',
    city: 'Miami',
    state: 'FL',
    phone: '(305) 555-0287',
    email: 'sales@precisionepoxy.com',
    rating: 'A',
    opportunityScore: 88,
    assignedRep: 'Sarah Mitchell',
    status: 'contacted',
    notes: 'Interested in residential garage epoxy systems',
    createdAt: '2024-01-13T09:15:00Z',
    category: 'Epoxy Specialists',
    address: '9012 South Beach Dr',
    revenue: 95000,
    lat: 25.7617,
    lng: -80.1918
  },
  {
    id: '4',
    company: 'Apex Construction Group',
    city: 'Jacksonville',
    state: 'FL',
    phone: '(904) 555-0341',
    email: 'info@apexconstruction.com',
    website: 'apexconstruction.com',
    rating: 'B+',
    opportunityScore: 82,
    status: 'new',
    createdAt: '2024-01-12T16:45:00Z',
    category: 'General Contractor',
    address: '3456 Builder Lane',
    revenue: 75000,
    lat: 30.3322,
    lng: -81.6557
  },
  {
    id: '5',
    company: 'Coastal Concrete & Repair',
    city: 'Clearwater',
    state: 'FL',
    phone: '(727) 555-0456',
    email: 'info@coastalconcrete.com',
    rating: 'B+',
    opportunityScore: 79,
    assignedRep: 'Mike Chen',
    status: 'new',
    notes: 'Small crew, mostly residential work',
    createdAt: '2024-01-11T11:30:00Z',
    category: 'Concrete Repair',
    address: '7890 Gulf Blvd',
    revenue: 62000,
    lat: 27.9659,
    lng: -82.8001
  },
  {
    id: '6',
    company: 'Superior Floor Systems',
    city: 'Tampa',
    state: 'FL',
    phone: '(813) 555-0512',
    email: 'contact@superiorfloorsystems.com',
    website: 'superiorfloorsystems.com',
    rating: 'A',
    opportunityScore: 90,
    assignedRep: 'Sarah Mitchell',
    status: 'qualified',
    notes: 'Premium installer with high-end clientele',
    createdAt: '2024-01-10T08:00:00Z',
    category: 'Flooring Installation',
    address: '2345 Enterprise Ct',
    revenue: 145000,
    lat: 27.9506,
    lng: -82.4572
  },
  {
    id: '7',
    company: 'Titan Coatings Inc',
    city: 'Fort Lauderdale',
    state: 'FL',
    phone: '(954) 555-0623',
    email: 'sales@titancoatings.com',
    rating: 'A+',
    opportunityScore: 94,
    status: 'contacted',
    createdAt: '2024-01-09T13:20:00Z',
    category: 'Industrial Coatings',
    address: '4567 Industrial Pkwy',
    revenue: 210000,
    lat: 26.1224,
    lng: -80.1373
  },
  {
    id: '8',
    company: 'Sunshine Epoxy Solutions',
    city: 'Sarasota',
    state: 'FL',
    phone: '(941) 555-0734',
    email: 'info@sunshineepoxy.com',
    website: 'sunshineepoxy.com',
    rating: 'B',
    opportunityScore: 75,
    assignedRep: 'Mike Chen',
    status: 'lost',
    notes: 'Price-sensitive, went with competitor',
    createdAt: '2024-01-08T15:45:00Z',
    category: 'Epoxy',
    address: '6789 Bay Shore Rd',
    revenue: 48000,
    lat: 27.3364,
    lng: -82.5307
  },
  {
    id: '9',
    company: 'ProFinish Concrete',
    city: 'St. Petersburg',
    state: 'FL',
    phone: '(727) 555-0845',
    email: 'contact@profinishconcrete.com',
    rating: 'A',
    opportunityScore: 86,
    assignedRep: 'Sarah Mitchell',
    status: 'proposal',
    notes: 'Requested detailed product specs and pricing',
    createdAt: '2024-01-07T10:10:00Z',
    category: 'Concrete Finishing',
    address: '8901 Central Ave',
    revenue: 112000,
    lat: 27.7676,
    lng: -82.6403
  },
  {
    id: '10',
    company: 'Premier Garage Floors',
    city: 'Naples',
    state: 'FL',
    phone: '(239) 555-0956',
    email: 'info@premiergaragefloors.com',
    website: 'premiergaragefloors.com',
    rating: 'A+',
    opportunityScore: 93,
    status: 'new',
    notes: 'High-volume residential garage epoxy specialist',
    createdAt: '2024-01-06T12:30:00Z',
    category: 'Garage Flooring',
    address: '1234 Paradise Dr',
    revenue: 165000,
    lat: 26.1420,
    lng: -81.7948
  },
  {
    id: '11',
    company: 'Industrial Floor Solutions',
    city: 'Tampa',
    state: 'FL',
    phone: '(813) 555-1067',
    email: 'sales@industrialfloors.com',
    rating: 'B+',
    opportunityScore: 80,
    assignedRep: 'Mike Chen',
    status: 'contacted',
    createdAt: '2024-01-05T09:45:00Z',
    category: 'Industrial Flooring',
    address: '3456 Factory Row',
    revenue: 88000,
    lat: 27.9506,
    lng: -82.4572
  },
  {
    id: '12',
    company: 'Emerald Coast Epoxy',
    city: 'Pensacola',
    state: 'FL',
    phone: '(850) 555-1178',
    email: 'info@emeraldcoastepoxy.com',
    website: 'emeraldcoastepoxy.com',
    rating: 'A',
    opportunityScore: 87,
    status: 'qualified',
    notes: 'Expanding into commercial market segment',
    createdAt: '2024-01-04T14:20:00Z',
    category: 'Epoxy Coatings',
    address: '5678 Beach Blvd',
    revenue: 125000,
    lat: 30.4213,
    lng: -87.2169
  }
]
